{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elk-frontend.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if ne .Values.persistence.storageClass "" }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}
{{- end }}