{{- if and .Values.gotosocial.persistence.enabled (eq .Values.gotosocial.persistence.existingClaim "") -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gotosocial.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.gotosocial.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.gotosocial.persistence.size | quote }}
{{- if .Values.gotosocial.persistence.storageClass }}
{{- if (eq "-" .Values.gotosocial.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.gotosocial.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}