apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gotosocial.fullname" . }}
stringData:
  {{- if .Values.externalPostgresql.ca_cert }}
    cert.crt: {{ .Values.externalPostgresql.ca_cert | quote }}
  {{- end }}
  config.yaml: |
    #  GoToSocial
    #  Copyright (C) 2021-2023 GoToSocial Authors admin@gotosocial.org
    #
    #  This program is free software: you can redistribute it and/or modify
    #  it under the terms of the GNU Affero General Public License as published by
    #  the Free Software Foundation, either version 3 of the License, or
    #  (at your option) any later version.
    #
    #  This program is distributed in the hope that it will be useful,
    #  but WITHOUT ANY WARRANTY; without even the implied warranty of
    #  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    #  GNU Affero General Public License for more details.
    #
    #  You should have received a copy of the GNU Affero General Public License
    #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
    ###########################
    ##### GENERAL CONFIG ######
    ###########################
    log-level: {{ .Values.gotosocial.config.logLevel | default "info" | quote }}
    log-db-queries: {{ .Values.gotosocial.config.logDBQueries | default false }}
    log-client-ip: {{ .Values.gotosocial.config.logClientIp | default false }}
    application-name: {{ .Values.gotosocial.config.applicationName | default "gotosocial" | quote }}
    landing-page-user: {{ .Values.gotosocial.config.landingPageUser | default "" |quote}}
    host: {{ .Values.gotosocial.config.host  |quote }}
    account-domain: {{ .Values.gotosocial.config.accountDomain | default "" |quote }}
    protocol: {{ .Values.gotosocial.config.protocol | default "https" |quote }}
    bind-address: {{ .Values.gotosocial.config.bindAddress | default "0.0.0.0" |quote }}
    port: {{ .Values.service.port | default 8080 }}
    trusted-proxies:
      - "127.0.0.1/32"
      - "::1"
    {{- range $.Values.gotosocial.config.trustedProxies }}
      - {{ . | title | quote }}
    {{- end }}
    ############################################
    ###### DATABASE CONFIG                ######
    ###### Some Settings are set via ENV  ######
    ############################################
    {{- if .Values.postgresql.enabled }}
    db-type: "postgres"
    db-address: "{{ include "gotosocial.postgresql.host" . }}"
    db-port: 5432
    db-user: "{{ .Values.postgresql.auth.username }}"
    db-database: "{{ .Values.postgresql.auth.database }}"
    {{- else if .Values.externalPostgresql.enabled }}
    db-type: "postgres"
    db-address: {{ .Values.externalPostgresql.host |quote }}
    db-port: {{ .Values.externalPostgresql.port }}
    db-user: {{ .Values.externalPostgresql.username |quote }}
    db-database: {{ .Values.externalPostgresql.database |quote }}
    db-tls-mode: "{{ .Values.externalPostgresql.tls_mode | default "disable" }}"
    {{- if .Values.externalPostgresql.ca_cert }}
    db-db-ca-cert: "/config/cert.crt"
    {{- end }}
    db-password: {{ .Values.externalPostgresql.password | quote }}
    {{- else }}
    db-type: sqlite
    db-address: {{ .Values.gotosocial.config.db.sqliteAddress | default "/gotosocial/storage/sqlite.db" |quote}}
    db-sqlite-journal-mode: {{ .Values.gotosocial.config.db.sqliteJournalMode | default "WAL" |quote }}
    db-sqlite-synchronous: {{ .Values.gotosocial.config.db.sqliteSynchronous | default "NORMAL" |quote }}
    db-sqlite-cache-size: {{ .Values.gotosocial.config.db.sqliteCacheSize | default "8MiB" |quote }}
    db-sqlite-busy-timeout: {{ .Values.gotosocial.config.db.sqliteBusyTimeout | default "30m" |quote }}
    {{- end }}
    db-max-open-conns-multiplier: {{ .Values.gotosocial.config.db.maxOpenConnsMultiplier | default 8 }}
    cache:
      memory-target: {{ .Values.gotosocial.config.db.cache.memoryTarget }}
    ######################
    ##### WEB CONFIG #####
    ######################
    web-template-base-dir: {{ .Values.gotosocial.config.web.templateBaseDir | default "./web/template/" |quote }}
    web-asset-base-dir: {{ .Values.gotosocial.config.web.assetBaseDir | default "./web/assets/" |quote }}
    accounts-custom-css-length: {{ .Values.gotosocial.config.web.accountsCustomCssLength | default 10000 }}
    ###########################
    ##### INSTANCE CONFIG #####
    ###########################
    instance-expose-peers: {{ .Values.gotosocial.config.instance.exposePeers | default false }}
    instance-expose-suspended: {{ .Values.gotosocial.config.instance.exposeSuspended | default false }}
    instance-expose-suspended-web: {{ .Values.gotosocial.config.instance.exposeSuspendedWeb | default false }}
    instance-expose-public-timeline: {{ .Values.gotosocial.config.instance.exposePublicTimeline | default false }}
    instance-deliver-to-shared-inboxes: {{ .Values.gotosocial.config.web.deliverToSharedInboxes | default true }}
    instance-inject-mastodon-version: {{ .Values.gotosocial.config.web.injectMastodonVersion | default false }}
    ###########################
    ##### ACCOUNTS CONFIG #####
    ###########################
    accounts-registration-open:  {{ .Values.gotosocial.config.accounts.registrationOpen | default true }}
    accounts-approval-required:  {{ .Values.gotosocial.config.accounts.approvalRequired | default true }}
    accounts-reason-required:  {{ .Values.gotosocial.config.accounts.reasonRequired | default true }}
    accounts-allow-custom-css: {{ .Values.gotosocial.config.accounts.allowCustomCSS | default false }}
    ########################
    ##### MEDIA CONFIG #####
    ########################
    media-image-max-size: {{ .Values.gotosocial.config.media.imageMaxSize | default 10485760 }}
    media-video-max-size: {{ .Values.gotosocial.config.media.videoMaxSize | default 41943040 }}
    media-description-min-chars: {{ .Values.gotosocial.config.media.descriptionMinChars | default 0 }}
    media-description-max-chars: {{ .Values.gotosocial.config.media.descriptionMaxChars | default 500 }}
    media-remote-cache-days: {{ .Values.gotosocial.config.media.mediaRemoteCacheDays | default 7 }}
    media-emoji-local-max-size: {{ .Values.gotosocial.config.media.emojiLocalMaxSize | default 51200 }}
    media-emoji-remote-max-size: {{ .Values.gotosocial.config.media.emojiRemoteMaxSize | default 51200 }}
    ##########################
    ##### STORAGE CONFIG #####
    ##########################
    storage-backend: {{ .Values.gotosocial.config.storage.backend | default "local" | quote }}
    storage-local-base-path: {{ .Values.gotosocial.config.storage.localBasePath | default "/gotosocial/storage" | quote }}
    {{- if .Values.gotosocial.config.storage.s3.enabled }}
    storage-s3-endpoint: {{ .Values.gotosocial.config.storage.s3.s3Endpoint | default "" }}
    storage-s3-proxy: {{ .Values.gotosocial.config.storage.s3.s3Proxy | default false }}
    storage-s3-use-ssl: {{ .Values.gotosocial.config.storage.s3.s3UseSSL | default true }}
    storage-s3-access-key: {{ .Values.gotosocial.config.storage.s3.s3AccessKey | default "" }}
    storage-s3-secret-key: {{ .Values.gotosocial.config.storage.s3.s3SecretKey | default "" }}
    storage-s3-bucket: {{ .Values.gotosocial.config.storage.s3.s3Bucket | default "" }}
    {{- end }}
    ###########################
    ##### STATUSES CONFIG #####
    ###########################
    statuses-max-chars: {{ .Values.gotosocial.config.statuses.maxChars | default 5000 }}
    statuses-cw-max-chars: {{ .Values.gotosocial.config.statuses.cwMaxChars | default 100 }}
    statuses-poll-max-options: {{ .Values.gotosocial.config.statuses.pollMaxOptions | default 6 }}
    statuses-poll-option-max-chars: {{ .Values.gotosocial.config.statuses.pollOptionMaxChars | default 50 }}
    statuses-media-max-files: {{ .Values.gotosocial.config.statuses.mediaMaxFiles | default 6 }}
    ##############################
    ##### LETSENCRYPT CONFIG #####
    ##############################
    letsencrypt-enabled: {{ .Values.gotosocial.config.letsencrypt.enabled | default false }}
    letsencrypt-port: {{ .Values.gotosocial.config.letsencrypt.port | default 80 }}
    letsencrypt-cert-dir: {{ .Values.gotosocial.config.letsencrypt.certDir | default "/gotosocial/storage/certs" | quote }}
    letsencrypt-email-address: {{ .Values.gotosocial.config.letsencrypt.emailAddress | default "" }}
    ##############################
    ##### MANUAL TLS CONFIG  #####
    ##############################
    tls-certificate-chain: {{ .Values.gotosocial.config.certificateChain | default "" | quote }}
    tls-certificate-key: {{ .Values.gotosocial.config.certificateKey | default "" | quote }}
    #######################
    ##### OIDC CONFIG #####
    #######################
    {{- if .Values.gotosocial.config.oidc.enabled }}
    oidc-enabled: {{ .Values.gotosocial.config.oidc.enabled | default false }}
    oidc-idp-name: {{ .Values.gotosocial.config.oidc.idpName | default "" }}
    oidc-skip-verification: {{ .Values.gotosocial.config.oidc.skipVerification | default false }}
    oidc-issuer: {{ .Values.gotosocial.config.oidc.issuer | default "" }}
    oidc-client-id: {{ .Values.gotosocial.config.oidc.clientID | default "" }}
    oidc-client-secret: {{ .Values.gotosocial.config.oidc.clientSecret | default "" }}
    oidc-scopes:
    {{- if .Values.gotosocial.config.oidc.oidcScopes -}}
      {{ .Values.gotosocial.config.oidc.oidcScopes | toYaml | nindent 6 }}
    {{- end }}
    oidc-link-existing: {{ .Values.gotosocial.config.oidc.linkExisting | default false }}
    oidc-admin-groups:
    {{- if .Values.gotosocial.config.oidc.adminGroups -}}
      {{ .Values.gotosocial.config.oidc.adminGroups | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
    #######################
    ##### SMTP CONFIG #####
    #######################
    smtp-host: {{ .Values.gotosocial.config.smtp.host | default "" }}
    smtp-port: {{ .Values.gotosocial.config.smtp.port | default 0 }}
    smtp-username: {{ .Values.gotosocial.config.smtp.userName | default "" }}
    {{- if .Values.gotosocial.config.smtp.password }}
    smtp-password: {{ .Values.gotosocial.config.smtp.password | default "" }}
    {{- end }}
    smtp-from: {{ .Values.gotosocial.config.smtp.from | default "" }}
    smtp-disclose-recipients: {{ .Values.gotosocial.config.smtp.discloseRecipients | default false }}
    #########################
    ##### SYSLOG CONFIG #####
    #########################
    syslog-enabled: {{ .Values.gotosocial.config.syslog.enabled | default false }}
    syslog-protocol: {{ .Values.gotosocial.config.syslog.protocol | default "tcp" |quote }}
    syslog-address: {{ .Values.gotosocial.config.syslog.address | default "localhost:514" |quote }}
    ##################################
    ##### OBSERVABILITY SETTINGS #####
    ##################################
    request-id-header: {{ .Values.gotosocial.config.observability.requestIdHeader | default "X-Request-Id" |quote }}
    tracing-enabled: {{ .Values.gotosocial.config.observability.tracing.enabled | default false }}
    tracing-transport: {{ .Values.gotosocial.config.observability.tracing.transport | default "" }}
    tracing-insecure-transport: {{ .Values.gotosocial.config.observability.tracing.insecureTransport | default false }}
    ################################
    ##### HTTP CLIENT SETTINGS #####
    ################################
    http-client:
      timeout: {{ .Values.gotosocial.config.httpClient.timeout | default "10s" |quote }}
      ########################################
      #### RESERVED IP RANGE EXCEPTIONS ######
      ########################################
      allow-ips: {{ .Values.gotosocial.config.httpClient.allowIPs }}
      block-ips: {{ .Values.gotosocial.config.httpClient.blockIPs }}
      tls-insecure-skip-verify: {{ .Values.gotosocial.config.httpClient.tlsInsecureSkipVerify | default false }}
    #############################
    ##### ADVANCED SETTINGS #####
    #############################
    advanced-cookies-samesite: {{ .Values.gotosocial.config.advanced.cookiesSamesite | default "lax" |quote  }}
    advanced-rate-limit-requests: {{ .Values.gotosocial.config.advanced.rateLimitRequests | default 300 }}
    advanced-throttling-multiplier: {{ .Values.gotosocial.config.advanced.throttlingMultiplier | default 8 }}
    advanced-throttling-retry-after: {{ .Values.gotosocial.config.advanced.throttlingRetryAfter | default "30s" }}
    advanced-sender-multiplier: {{ .Values.gotosocial.config.advanced.advancedSenderMultiplier | default 2 }}
    ########################
    ##### Extra config #####
    ########################
    {{- with .Values.extraConfig }}
    ## Extra config ##
    {{ . | toYaml | nindent 4 }}
    {{- end }}%
