{{- if eq .Values.refactoringAccepted "" }}
{{- fail "The Chart was refactored, please Check the README and the values.yaml" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gotosocial.fullname" . }}
stringData:
  {{- if ne .Values.externalPostgresql.ca_cert "" }}
  cert.crt: {{ .Values.externalPostgresql.ca_cert | quote }}
  {{- end }}
  config.yaml: |
    ###########################
    ##### GENERAL CONFIG ######
    ###########################
    # String. Hostname that this server will be reachable at. Defaults to localhost for local testing,
    # but you should *definitely* change this when running for real, or your server won't work at all.
    # DO NOT change this after your server has already run once, or you will break things!
    # Examples: ["gts.example.org","some.server.com"]
    # Default: "localhost"
    host: {{ required ".Values.gotosocial.config.host should not be empty check: https://github.com/superseriousbusiness/gotosocial/blob/f1cbf6fb761670e10eb8e3fecdc57578733186a1/example/config.yaml#L60 or set localhost" .Values.gotosocial.config.host  | quote }}
    account-domain: {{ .Values.gotosocial.config.accountDomain | default "" |quote }}
    protocol: {{ .Values.gotosocial.config.protocol | quote }}
    bind-address: {{ .Values.gotosocial.config.bindAddress | quote }}
    port: {{ .Values.service.port }}
    trusted-proxies:
    {{- range $.Values.gotosocial.config.trustedProxies }}
      - "127.0.0.1/32"
      - {{ . | title | quote }}
    {{- end }}
    ############################################
    ###### DATABASE CONFIG                ######
    ###### Some Settings are set via ENV  ######
    ############################################
    {{- if .Values.postgresql.enabled }}
    db-type: "postgres"
    db-address: "{{ include "gotosocial.postgresql.host" . }}"
    db-port: 5432
    db-user: "{{ .Values.postgresql.auth.username }}"
    db-database: "{{ .Values.postgresql.auth.database }}"
    {{- else if .Values.externalPostgresql.enabled }}
    db-type: "postgres"
    db-address: {{ .Values.externalPostgresql.host |quote }}
    db-port: {{ .Values.externalPostgresql.port }}
    db-user: {{ .Values.externalPostgresql.username |quote }}
    db-database: {{ .Values.externalPostgresql.database |quote }}
    db-tls-mode: "{{ .Values.externalPostgresql.tls_mode | default "disable" }}"
    {{- if .Values.externalPostgresql.ca_cert }}
    db-db-ca-cert: "/config/cert.crt"
    {{- end }}
    db-password: {{ .Values.externalPostgresql.password | quote }}
    {{- else }}
    db-type: sqlite
    db-address: {{ .Values.sqLite.address | default "/gotosocial/storage/sqlite.db" |quote}}
    db-sqlite-journal-mode: {{ .Values.sqLite.journalMode | default "WAL" |quote }}
    db-sqlite-synchronous: {{ .Values.sqLite.synchronous | default "NORMAL" |quote }}
    db-sqlite-cache-size: {{ .Values.sqLite.cacheSize | default "8MiB" |quote }}
    db-sqlite-busy-timeout: {{ .Values.sqLite.busyTimeout | default "30m" |quote }}
    {{- end }}
    db-max-open-conns-multiplier: {{ .Values.gotosocial.config.db.maxOpenConnsMultiplier }}
    cache:
      memory-target: {{ .Values.gotosocial.config.db.cache.memoryTarget }}
    ##########################
    ##### STORAGE CONFIG #####
    ##########################
    storage-backend: {{ .Values.gotosocial.config.storage.backend | default "local" | quote }}
    storage-local-base-path: {{ .Values.gotosocial.config.storage.localBasePath | default "/gotosocial/storage" | quote }}
    {{- if .Values.gotosocial.config.storage.s3.enabled }}
    storage-s3-endpoint: {{ .Values.gotosocial.config.storage.s3.endpoint | default "" }}
    storage-s3-proxy: {{ .Values.gotosocial.config.storage.s3.proxy | default false }}
    storage-s3-use-ssl: {{ .Values.gotosocial.config.storage.s3.useSSL | default true }}
    {{- if eq .Values.gotosocial.config.storage.s3.existingSecret "" }}
    storage-s3-access-key: {{ .Values.gotosocial.config.storage.s3.accessKey | default "" }}
    storage-s3-secret-key: {{ .Values.gotosocial.config.storage.s3.secretKey | default "" }}
    {{- end }}
    storage-s3-bucket: {{ .Values.gotosocial.config.storage.s3.bucket | default "" }}
    {{- end }}
    #######################
    ##### OIDC CONFIG #####
    #######################
    {{- if .Values.gotosocial.config.oidc.enabled }}
    oidc-enabled: {{ .Values.gotosocial.config.oidc.enabled | default false }}
    oidc-idp-name: {{ .Values.gotosocial.config.oidc.idpName | default "" }}
    oidc-skip-verification: {{ .Values.gotosocial.config.oidc.skipVerification | default false }}
    oidc-issuer: {{ .Values.gotosocial.config.oidc.issuer | default "" }}
    oidc-client-id: {{ .Values.gotosocial.config.oidc.clientID | default "" }}
    oidc-client-secret: {{ .Values.gotosocial.config.oidc.clientSecret | default "" }}
    oidc-scopes:
    {{- if .Values.gotosocial.config.oidc.oidcScopes -}}
      {{ .Values.gotosocial.config.oidc.oidcScopes | toYaml | nindent 6 }}
    {{- end }}
    oidc-link-existing: {{ .Values.gotosocial.config.oidc.linkExisting | default false }}
    oidc-admin-groups:
    {{- if .Values.gotosocial.config.oidc.adminGroups -}}
      {{ .Values.gotosocial.config.oidc.adminGroups | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
    #######################
    ##### SMTP CONFIG #####
    #######################
    smtp-host: {{ .Values.gotosocial.config.smtp.host | default "" }}
    smtp-port: {{ .Values.gotosocial.config.smtp.port | default 0 }}
    smtp-username: {{ .Values.gotosocial.config.smtp.userName | default "" }}
    {{- if eq .Values.gotosocial.config.smtp.existingSecretName "" }}
    smtp-password: {{ .Values.gotosocial.config.smtp.password | default "" }}
    {{- end }}
    smtp-from: {{ .Values.gotosocial.config.smtp.from | default "" }}
    smtp-disclose-recipients: {{ .Values.gotosocial.config.smtp.discloseRecipients | default false }}
    {{- with .Values.gotosocial.extraConfig }}
    ########################
    ##### Extra config #####
    ########################
    {{- . | toYaml | nindent 4 }}
    {{- end }}
