apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gotosocial.fullname" . }}
stringData:
  {{- if .Values.externalPostgresql.ca_cert }}
    cert.crt: {{ .Values.externalPostgresql.ca_cert | quote }}
  {{- end }}
  config.yaml: |
    ###########################
    ##### GENERAL CONFIG ######
    ###########################
    log-level: {{ .Values.gotosocial.config.logLevel | default "info" | quote }}
    log-db-queries: {{ .Values.gotosocial.config.logDBQueries | default false }}
    application-name: {{ .Values.gotosocial.config.applicationName | default "gotosocial" | quote }}
    landing-page-user: {{ .Values.gotosocial.config.landingPageUser | default "" |quote}}
    host: {{ .Values.gotosocial.config.host | default "localhost"  |quote }}
    account-domain: {{ .Values.gotosocial.config.accountDomain | default "" |quote }}
    protocol: {{ .Values.gotosocial.config.protocol | default "https" |quote }}
    bind-address: {{ .Values.gotosocial.config.bindAddress | default "0.0.0.0" |quote }}
    port: {{ .Values.service.port | default 8080 }}
    trusted-proxies:
      - "127.0.0.1/32"
      - "::1"
    {{- if .Values.gotosocial.config.trustedProxies -}}
      {{ .Values.gotosocial.config.trustedProxies | toYaml | nindent 6 }}
    {{- end }}
    ############################################
    ###### DATABASE CONFIG                ######
    ###### Some Settings are set via ENV  ######
    ############################################
    {{- if .Values.postgresql.enabled }}
    db-type: "postgres"
    db-address: "{{ include "gotosocial.postgresql.host" . }}"
    db-port: 5432
    db-user: "{{ .Values.postgresql.auth.username }}"
    db-database: "{{ .Values.postgresql.auth.database }}"
    {{- else if .Values.externalPostgresql.enabled }}
    db-type: "postgres"
    db-address: {{ .Values.externalPostgresql.host |quote }}
    db-port: {{ .Values.externalPostgresql.port }}
    db-user: {{ .Values.externalPostgresql.username |quote }}
    db-database: {{ .Values.externalPostgresql.database |quote }}
    db-tls-mode: "{{ .Values.externalPostgresql.tls_mode | default "disable" }}"
    {{- if .Values.externalPostgresql.ca_cert }}
    db-db-ca-cert: "/config/cert.crt"
    {{- end }}
    db-password: {{ .Values.externalPostgresql.password | quote }}
    {{- else }}
    db-type: sqlite
    db-address: {{ .Values.gotosocial.config.db.sqlite_address | default "/gotosocial/storage/sqlite.db" |quote}}
    db-sqlite-journal-mode: {{ .Values.gotosocial.config.db.sqliteJournalMode | default "WAL" |quote }}
    db-sqlite-synchronous: {{ .Values.gotosocial.config.db.sqliteSynchronous | default "NORMAL" |quote }}
    db-sqlite-cache-size: {{ .Values.gotosocial.config.db.sqliteCacheSize | default "8MiB" |quote }}
    db-sqlite-busy-timeout: {{ .Values.gotosocial.config.db.sqliteBusyTimeout | default "5m" |quote }}
    {{- end }}
    db-max-open-conns-multiplier: {{ .Values.gotosocial.config.db.maxOpenConnsMultiplier | default 8 }}
    {{- if .Values.gotosocial.config.db.cache.enabled }}
    cache:
      gts:
        account-max-size: {{ .Values.gotosocial.config.db.cache.gts.accountMaxSize | default 100 }}
        account-ttl: {{ .Values.gotosocial.config.db.cache.gts.accountTTl | default "5m" | quote }}
        account-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.accountSweepFreq | default "10s" | quote }}
        block-max-size: {{ .Values.gotosocial.config.db.cache.gts.blockMaxSize | default 100 }}
        block-ttl: {{ .Values.gotosocial.config.db.cache.gts.blockTTl | default "5m" | quote }}
        block-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.blockSweepFreq | default "10s" | quote }}
        domain-block-max-size: {{ .Values.gotosocial.config.db.cache.gts.domainBlockMaxSize | default 1000 }}
        domain-block-ttl: {{ .Values.gotosocial.config.db.cache.gts.domainBlockTTl | default "24h" | quote }}
        domain-block-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.domainBlockSweepFreq | default "1m" | quote }}
        emoji-max-size: {{ .Values.gotosocial.config.db.cache.gts.emojiMaxSize | default 500 }}
        emoji-ttl: {{ .Values.gotosocial.config.db.cache.gts.emojiTTl | default "5m" |quote }}
        emoji-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.emojiSweepFreq | default "10s" |quote }}
        emoji-category-max-size: {{ .Values.gotosocial.config.db.cache.gts.emojiCategoryMaxSize | default 100 }}
        emoji-category-ttl: {{ .Values.gotosocial.config.db.cache.gts.emojiCategoryTTl | default "5m" | quote }}
        emoji-category-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.emojiCategorySweepFreq | default "10s" | quote }}
        mention-max-size: {{ .Values.gotosocial.config.db.cache.gts.mentionMaxSize | default 500 }}
        mention-ttl:  {{ .Values.gotosocial.config.db.cache.gts.mentionTTl | default "5m" | quote }}
        mention-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.mentionSweepFreq | default "10s" | quote }}
        notification-max-size: {{ .Values.gotosocial.config.db.cache.gts.notificationMaxSize | default 500 }}
        notification-ttl: {{ .Values.gotosocial.config.db.cache.gts.notificationTTl | default "5m" | quote }}
        notification-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.notificationSweepFreq | default "10s" | quote }}
        report-max-size:: {{ .Values.gotosocial.config.db.cache.gts.reportMaxSize | default 100 }}
        report-ttl: {{ .Values.gotosocial.config.db.cache.gts.reportTTl | default "5m" | quote }}
        report-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.reportSweepFreq | default "10s" | quote }}
        status-max-size: {{ .Values.gotosocial.config.db.cache.gts.statusMaxSize | default 500 }}
        status-ttl: {{ .Values.gotosocial.config.db.cache.gts.statusTTl | default "5m" | quote }}
        status-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.statusSweepFreq | default "10s" | quote }}
        tombstone-max-size: {{ .Values.gotosocial.config.db.cache.gts.tombstoneMaxSize | default 100 }}
        tombstone-ttl: {{ .Values.gotosocial.config.db.cache.gts.tombstoneTTl | default "5m" | quote }}
        tombstone-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.tombstoneSweepFreq | default "10s" | quote }}
        user-max-size: {{ .Values.gotosocial.config.db.cache.gts.userMaxSize | default 100 }}
        user-ttl: {{ .Values.gotosocial.config.db.cache.gts.userTTl | default "5m" | quote }}
        user-sweep-freq: {{ .Values.gotosocial.config.db.cache.gts.userSweepFreq | default "10s" | quote }}
    {{- end }}
    ######################
    ##### WEB CONFIG #####
    ######################
    web-template-base-dir: {{ .Values.gotosocial.config.web.templateBaseDir | default "./web/template/" |quote }}
    web-asset-base-dir: {{ .Values.gotosocial.config.web.assetBaseDir | default "./web/assets/" |quote }}
    ###########################
    ##### INSTANCE CONFIG #####
    ###########################
    instance-expose-peers: {{ .Values.gotosocial.config.instance.instanceExposePeers | default false }}
    instance-expose-suspended: {{ .Values.gotosocial.config.instance.instanceExposeSuspended | default false }}
    instance-expose-public-timeline: {{ .Values.gotosocial.config.instance.instanceExposePublicTimeline | default false }}
    instance-deliver-to-shared-inboxes: {{ .Values.gotosocial.config.web.instanceDeliverToSharedInboxes | default true }}
    ###########################
    ##### ACCOUNTS CONFIG #####
    ###########################
    accounts-registration-open:  {{ .Values.gotosocial.config.accounts.registrationOpen | default true }}
    accounts-approval-required:  {{ .Values.gotosocial.config.accounts.approvalRequired | default true }}
    accounts-reason-required:  {{ .Values.gotosocial.config.accounts.reasonRequired | default true }}
    accounts-allow-custom-css: {{ .Values.gotosocial.config.accounts.allowCustomCSS | default false }}
    ########################
    ##### MEDIA CONFIG #####
    ########################
    media-image-max-size: {{ .Values.gotosocial.config.media.imageMaxSize | default 10485760 }}
    media-video-max-size: {{ .Values.gotosocial.config.media.videoMaxSize | default 41943040 }}
    media-description-min-chars: {{ .Values.gotosocial.config.media.descriptionMinChars | default 0 }}
    media-description-max-chars: {{ .Values.gotosocial.config.media.descriptionMaxChars | default 500 }}
    media-remote-cache-days: {{ .Values.gotosocial.config.media.mediaRemoteCacheDays | default 30 }}
    media-emoji-local-max-size: {{ .Values.gotosocial.config.media.emojiLocalMaxSize | default 51200 }}
    media-emoji-remote-max-size: {{ .Values.gotosocial.config.media.emojiRemoteMaxSize | default 102400 }}
    ##########################
    ##### STORAGE CONFIG #####
    ##########################
    storage-backend: {{ .Values.gotosocial.config.storage.backend | default "local" }}
    storage-local-base-path: {{ .Values.gotosocial.config.storage.localBasePath | default "/gotosocial/storage" |quote }}
    {{- if .Values.gotosocial.config.storage.s3.enabled }}
    storage-s3-endpoint: {{ .Values.gotosocial.config.storage.s3.s3Endpoint | default "" }}
    storage-s3-proxy: {{ .Values.gotosocial.config.storage.s3.s3Proxy | default false }}
    storage-s3-use-ssl: {{ .Values.gotosocial.config.storage.s3.s3UseSSL | default true }}
    storage-s3-access-key: {{ .Values.gotosocial.config.storage.s3.s3AccessKey | default "" }}
    storage-s3-secret-key: {{ .Values.gotosocial.config.storage.s3.s3SecretKey | default "" }}
    storage-s3-bucket: {{ .Values.gotosocial.config.storage.s3.s3Bucket | default "" }}
    {{- end }}
    ###########################
    ##### STATUSES CONFIG #####
    ###########################
    statuses-max-chars: {{ .Values.gotosocial.config.statuses.maxChars | default 5000 }}
    statuses-cw-max-chars: {{ .Values.gotosocial.config.statuses.cwMaxChars | default 100 }}
    statuses-poll-max-options: {{ .Values.gotosocial.config.statuses.pollMaxOptions | default 6 }}
    statuses-poll-option-max-chars: {{ .Values.gotosocial.config.statuses.pollOptionMaxChars | default 50 }}
    statuses-media-max-files: {{ .Values.gotosocial.config.statuses.mediaMaxFiles | default 6 }}
    ##############################
    ##### LETSENCRYPT CONFIG #####
    ##############################
    letsencrypt-enabled: {{ .Values.gotosocial.config.letsencrypt.enabled | default false }}
    letsencrypt-port: {{ .Values.gotosocial.config.letsencrypt.port | default 80 }}
    letsencrypt-cert-dir: {{ .Values.gotosocial.config.letsencrypt.certDir | default "/gotosocial/storage/certs" |quote }}
    letsencrypt-email-address: {{ .Values.gotosocial.config.letsencrypt.emailAddress | default "" }}
    #######################
    ##### OIDC CONFIG #####
    #######################
    {{- if .Values.gotosocial.config.oidc.enabled }}
    oidc-enabled: {{ .Values.gotosocial.config.oidc.enabled | default false }}
    oidc-idp-name: {{ .Values.gotosocial.config.oidc.idpName | default "" }}
    oidc-skip-verification: {{ .Values.gotosocial.config.oidc.skipVerification | default false }}
    oidc-issuer: {{ .Values.gotosocial.config.oidc.issuer | default "" }}
    oidc-client-id: {{ .Values.gotosocial.config.oidc.clientID | default "" }}
    oidc-client-secret: {{ .Values.gotosocial.config.oidc.clientSecret | default "" }}
    oidc-scopes:
    {{- if .Values.gotosocial.config.oidc.oidcScopes -}}
      {{ .Values.gotosocial.config.oidc.oidcScopes | toYaml | nindent 6 }}
    {{- end }}
    oidc-link-existing: {{ .Values.gotosocial.config.oidc.linkExisting | default false }}
    {{- end }}
    #######################
    ##### SMTP CONFIG #####
    #######################
    smtp-host: {{ .Values.gotosocial.config.smtp.host | default "" }}
    smtp-port: {{ .Values.gotosocial.config.smtp.port | default 0 }}
    smtp-username: {{ .Values.gotosocial.config.smtp.userName | default "" }}
    {{- if .Values.gotosocial.config.smtp.password }}
    smtp-password: {{ .Values.gotosocial.config.smtp.password | default "" }}
    {{- end }}
    smtp-from: {{ .Values.gotosocial.config.smtp.from | default "" }}
    #########################
    ##### SYSLOG CONFIG #####
    #########################
    syslog-enabled: {{ .Values.gotosocial.config.syslog.enabled | default false }}
    syslog-protocol: {{ .Values.gotosocial.config.syslog.protocol | default "udp" |quote }}
    syslog-address: {{ .Values.gotosocial.config.syslog.address | default "localhost:514" |quote }}
    ##################################
    ##### OBSERVABILITY SETTINGS #####
    ##################################
    request-id-header: {{ .Values.gotosocial.config.observability.requestIdHeader | default "X-Request-Id" |quote }}
    #############################
    ##### ADVANCED SETTINGS #####
    #############################
    advanced-cookies-samesite: {{ .Values.gotosocial.config.advanced.cookiesSamesite | default "lax" |quote  }}
    advanced-rate-limit-requests: {{ .Values.gotosocial.config.advanced.rateLimitRequests | default 300 }}
    advanced-throttling-multiplier: {{ .Values.gotosocial.config.advanced.throttlingMultiplier | default 8 }}
    advanced-throttling-retry-after: {{ .Values.gotosocial.config.advanced.throttlingRetryAfter | default "30s" }}
    ########################
    ##### Extra config #####
    ########################
    {{- with .Values.extraConfig }}
    ## Extra config ##
    {{ . | toYaml | nindent 4 }}
    {{- end }}%
