apiVersion: v2
name: linkwarden
description: A Helm chart for Kubernetes
icon: https://docs.linkwarden.app/img/logo.png
home: https://github.com/linkwarden/linkwarden

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v2.10.1"

# Chart maintainers, contributors, and related metadata.
maintainers:
  - name: 0hlov3
    email: dev@privatetrace.io
    url: https://schoenwald.aero

# Sources for the application, such as repositories or documentation.
sources:
  - https://github.com/linkwarden/linkwarden
  - https://docs.linkwarden.app/