# Default values for linkwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
## @section image parameters
image:
  ## @param image.registry image registry
  registry: ghcr.io
  ## @param image.repository image repository
  repository: linkwarden/linkwarden
  # This sets the pull policy for images.
  ## @param image.pullPolicy image pull policy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  ## @skip image.tag image tag (immutable tags are recommended)
  tag: ""

## @section Linkwarden Environment Config
env:
  nextauth:
    ## @param env.nextauth.url Defines the NEXTAUTH_URL and specifies the base URL for NextAuth.js authentication endpoints.
    url: "http://localhost:3000/api/v1/auth"
    ## @param env.nextauth.secret Defines the NEXTAUTH_SECRET and is used by NextAuth.js to encrypt session tokens and JWTs. Can be generatet via `openssl rand -base64 32`
    secret: ""
    existingSecret:
      ## @param env.nextauth.existingSecret.name Defines the NEXTAUTH_SECRET kubernetes secret name where to get the secret.
      name: ""
      ## @param env.nextauth.existingSecret.key Defines the NEXTAUTH_SECRET kubernetes secret key where to get the secret.
      key: ""

## @param extraEnv additional environment variables to pass to the Linkwarden deployment
extraEnv: []
  #- name: NEXT_PUBLIC_DISABLE_REGISTRATION
  #  value: "true"
  # - name: NEXT_PUBLIC_CREDENTIALS_ENABLED
  #   value: "true"
  #- name: DISABLE_NEW_SSO_USERS
  #  value: "true"
  #- name: NEXT_PUBLIC_EMAIL_PROVIDER
  #  value: ""
  #- name: EMAIL_FROM
  #  value: ""
  #- name: EMAIL_SERVER
  #  value: ""
  #- name: BASE_URL
  #  value: ""
  # Zitadel
  # NEXT_PUBLIC_ZITADEL_ENABLED=
  # ZITADEL_CUSTOM_NAME=
  # ZITADEL_CLIENT_ID=
  # ZITADEL_CLIENT_SECRET=
  # ZITADEL_ISSUER=

#######################
## @section Persistence
#######################
persistence:
  ## @param persistence.enabled Enable persistence mediaStore, if false refers to emptyDir (not recommended).
  enabled: false
  ## @param persistence.size Defines the Size of Peristant volume for Linkwarden data.
  size: 1Gi
  ## @param persistence.accessMode Enable persistence for SQLite data.
  accessMode: ReadWriteOnce
  ## @param persistence.storageClassName If empty uses the default storageClass.
  storageClassName: ""
##################################
## @section Database Configuration
##################################
externalPostgresql:
  ## @param externalPostgresql.enabled Enable external PostgreSQL as the database backend.
  ## Default: false
  enabled: true
  ## @param externalPostgresql.host Hostname of the external PostgreSQL database.
  ## Default: postgresql.postgresql.svc.cluster.local
  host: postgresql.postgresql.svc.cluster.local
  ## @param externalPostgresql.port Port for the external PostgreSQL database.
  ## Default: 5432
  port: "5432"
  ## @param externalPostgresql.database Name of the database to use.
  ## Default: linkwarden
  database: linkwarden
  ## @param externalPostgresql.username Username of the database to use.
  ## Default: linkwarden
  username: ""
  ## @param externalPostgresql.password Password of the database to use.
  ## Default: linkwarden
  password: ""
  existingSecret:
    ## @param externalPostgresql.existingSecret.name Name of an existing Kubernetes secret containing database credentials.
    ## Default: ""
    name: ""
    keys:
      ## @param externalPostgresql.existingSecret.keys.host Key for the host in the existing secret.
      ## Default: ""
      host: ""
      ## @param externalPostgresql.existingSecret.keys.port Key for the port in the existing secret.
      ## Default: ""
      port: ""
      ## @param externalPostgresql.existingSecret.keys.database Key for the port in the existing secret.
      ## Default: ""
      database: ""
      ## @param externalPostgresql.existingSecret.keys.username Key for the username in the existing secret.
      ## Default: ""
      username: ""
      ## @param externalPostgresql.existingSecret.keys.password Key for the password in the existing secret.
      ## Default: ""
      password: ""

## @section Traffic Exposure Parameters
# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  ## @param service.type Service type
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  ## @param service.port service port
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  ## @param ingress.enabled Enable ingress record generation for 
  enabled: false
  ## @param ingress.className IngressClass that will be used to implement the Ingress
  className: ""
  ## @param ingress.annotations Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations.
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt"
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # ingress.hosts An array with additional arbitrary host and paths that may need to be added to the ingress under the main host
  hosts:
    ## @skip  ingress.hosts[0]
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  ## @param ingress.tls TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

###################
## @section General
###################
## @param imagePullSecrets Global registry secret names as an array
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
## @param nameOverride String to partially override common.names.fullname
# This is to override the chart name.
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  ## @param serviceAccount.create Specifies whether a ServiceAccount should be created
  # Specifies whether a service account should be created
  create: true
  ## @param serviceAccount.automount Automount service account token for the server service account
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  ## @param serviceAccount.annotations Additional custom annotations for the ServiceAccount
  # Annotations to add to the service account
  annotations: {}
  ## @param serviceAccount.name The name of the ServiceAccount to use.
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## @param podAnnotations Annotations for pods
# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
## @param podLabels Labels for pods
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

## @param podSecurityContext podSecurityContext for pods
podSecurityContext: {}
  # fsGroup: 2000

## @param securityContext securityContext for pods
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## @param resources Set container requests and limits for different resources like CPU or memory (essential for production workloads)
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
## @skip livenessProbe
livenessProbe:
  httpGet:
    path: /
    port: http
## @skip readinessProbe
readinessProbe:
  httpGet:
    path: /
    port: http

## @skip volumes
# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
## @skip volumeMounts
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
## @skip nodeSelector
nodeSelector: {}
## @skip tolerations
tolerations: []
## @skip affinity
affinity: {}