apiVersion: v2
name: elk-frontend
description: A Helm chart for Kubernetes to deploy Elk in Kubernetes.
icon: https://raw.githubusercontent.com/elk-zone/elk/main/public/logo.svg
home: https://github.com/elk-zone/elk
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.16

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.15.1"

maintainers:
  - name: 0hlov3
    email: dev@privatetrace.io
    url: https://schoenwald.aero