{{ $fullName := include "matrix-synapse.fullname" . }}
{{ $registrationSharedSecret := include "matrix-synapse.registration_shared_secret" . }}
{{ $macaroonSecretKey := include "matrix-synapse.macaroon_secret_key" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
stringData:
  config.yaml: |-
    {{- if .Values.config.server.email.enabled }}
    ###########
    ## email ##
    ###########
    email:
      smtp_host: "@@@SMTPHOST@@@"
      smtp_port: "@@@SMTPPORT@@@"
      smtp_user: "@@@SMTPUSER@@@"
      smtp_pass: "@@@SMTPPASSWORD@@@"
      force_tls: {{ .Values.config.server.email.force_tls }}
      require_transport_security: {{ .Values.config.server.email.require_transport_security }}
      enable_tls: {{ .Values.config.server.email.enable_tls }}
      notif_from: {{ .Values.config.server.email.notif_from }}
      enable_notifs: {{ .Values.config.server.email.enable_notifs }}
      client_base_url: {{ .Values.config.server.email.client_base_url }}
    {{- end }}
    ############################
    ## Database configuration ##
    ############################
    database:
      {{- if and .Values.sqlite.enabled (not .Values.externalPostgresql.enabled) }}
      name: sqlite3
      args:
        database: /synapse/sqlite/homeserver.db
      {{- else if .Values.externalPostgresql.enabled }}
      name: psycopg2
      args:
        user: @@@POSTGRESUSER@@@
        password: @@@POSTGRESPASSWORD@@@
        database: @@@POSTGRESDATABASE@@@
        host: @@@POSTGRESHOST@@@
        port: @@@POSTGRESPORT@@@
      {{- end }}
    ##################
    ## Registration ##
    ##################
    {{- if ne $registrationSharedSecret "false" }}
    registration_shared_secret: @@@REGISTRATIONSHAREDSECRET@@@
    {{- end }}
    #######################
    ## API Configuration ##
    #######################
    {{- if ne $macaroonSecretKey "false" }}
    macaroon_secret_key: @@@MACAROONSECRETKEY@@@
    {{- end }}
    #############
    ## Captcha ##
    #############