{{- $bindAddresses := .Values.config.bindAddresses | default (list "::") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-synapse.fullname" . }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
data:
  homeserver.yaml: |-
    #######################################################################
    ## NOTE:                                                             ##
    ## Secrets are stored in separate configs to better fit K8s concepts ##
    #######################################################################
    ######################################################################################################
    ## Server                                                                                           ##
    ## https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#server ##
    ######################################################################################################
    server_name: {{ required "You need to specify a serverName" .Values.config.serverName | quote }}
    public_baseurl: {{ .Values.config.publicBaseurl | default (printf "https://%s" (.Values.publicServerName | default .Values.serverName)) | quote }}
    pid_file: /homeserver.pid
    {{- if .Values.config.webClientLocation }}
    web_client_location: {{ .Values.config.webClientLocation }}
    {{- end }}
    serve_server_wellknown: {{ .Values.config.serveServerWellknown }}
    soft_file_limit: {{ .Values.config.softFileLimit }}
    log_config: "/synapse/config/log.yaml"
    report_stats: {{ required "You need to specify config.reportStats" .Values.config.reportStats }}
    ## Ports ##
    listeners:
      - port: 8008
        tls: false
        bind_addresses: {{ toJson $bindAddresses }}
        type: http
        x_forwarded: true
        resources:
          - names:
              - client
              - federation
            compress: false
      {{- if .Values.metrics.enabled }}
      - port: 9090
        tls: false
        bind_addresses: {{ toJson $bindAddresses }}
        type: http
        resources:
          - names: [metrics]
            compress: false
      {{- end }}
      - port: 9093
        tls: false
        bind_addresses: {{ toJson $bindAddresses }}
        type: http
        resources:
          - names: [replication]
            compress: false
    {{- if .Values.config.extraListeners }}
      {{ .Values.config.extraListeners | toYaml | nindent 6 }}
    {{- end }}
    ###########################################################################################################
    ## Media Store                                                                                           ##
    ## https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#media-store ##
    ###########################################################################################################
    enable_media_repo: {{ .Values.config.mediaStore.enabled }}
    media_store_path: "/synapse/data/media"
    uploads_path: "/synapse/data/uploads"
    {{- if .Values.config.captcha.enabled }}
    #######################################################################################################
    ## Captcha                                                                                           ##
    ## https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#captcha ##
    #######################################################################################################
    enable_registration_captcha: true
    {{- end }}
    {{- if .Values.config.registration.enabled }}
    ############################################################################################################
    ## Registration                                                                                           ##
    ## https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#registration ##
    ############################################################################################################
    enable_registration: {{ .Values.config.registration.enabled }}
    enable_registration_without_verification: {{ .Values.config.registration.withoutVerification }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    #######################################################################################################
    ## Metrics                                                                                           ##
    ## https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#metrics ##
    #######################################################################################################
    enable_metrics: {{ .Values.metrics.enabled }}
    {{- end }}
    ############################################################################################################
    ## Signing Keys                                                                                           ##
    ## https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#signing-keys ##
    ############################################################################################################
    signing_key_path: "/synapse/keys/signing.key"
    trusted_key_servers: {{- .Values.config.trustedKeyServers | toYaml | nindent 6 }}
    {{- with .Values.extraConfig }}
    ##################
    ## Extra config ##
    ##################
    {{ . | toYaml | nindent 4 }}
    {{- end }}

