{{- $signingKeyJobEnabled := include "matrix-synapse.checkSigningKeyConfiguration" . | trim -}}
{{- if eq $signingKeyJobEnabled "true" }}
{{ $name := include "matrix-synapse.signingKeyFullName" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-scripts
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    {{- include "matrix-synapse.signingKeylabels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/*.sh").AsConfig | indent 2 }}
{{- end }}