{{- $signingKeyJobEnabled := include "matrix-synapse.checkSigningKeyConfiguration" . | trim -}}
{{- if eq $signingKeyJobEnabled "true" }}
{{ $name := include "matrix-synapse.signingKeyFullName" . }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    {{- include "matrix-synapse.signingKeylabels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      labels:
        {{- include "matrix-synapse.signingKeylabels" . | nindent 8 }}
    spec:
      containers:
        - command:
            - sh
            - -c
            - |
              echo "Generating signing key..."
              if which generate_signing_key.py >/dev/null; then
                generate_signing_key.py -o /synapse/keys/signing.key
              else
                generate_signing_key -o /synapse/keys/signing.key
              fi
          image: "{{ .Values.image.registry}}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: signing-key-generate
          resources:
            {{- toYaml .Values.signingkey.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /synapse/keys
              name: synapse-keys
        - command:
            - sh
            - -c
            - |
              printf "Checking rights to update secret... "
              kubectl auth can-i update secret/${SECRET_NAME}
              /scripts/signingkey.sh
          env:
            - name: SECRET_NAME
              value: {{ $name }}
          image: "{{ .Values.signingkey.job.storeSecretImage.registry }}/{{ .Values.signingkey.job.storeSecretImage.repository }}:{{ .Values.signingkey.job.storeSecretImage.tag }}"
          imagePullPolicy: {{ .Values.signingkey.job.storeSecretImage.pullPolicy }}
          name: signing-key-upload
          resources:
            {{- toYaml .Values.signingkey.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /scripts
              name: scripts
              readOnly: true
            - mountPath: /synapse/keys
              name: synapse-keys
              readOnly: true
      restartPolicy: Never
      serviceAccountName: {{ $name }}
      volumes:
        - name: scripts
          configMap:
            name: {{ $name }}-scripts
            defaultMode: 0755
        - name: synapse-keys
          emptyDir: {}
  parallelism: 1
  completions: 1
  backoffLimit: 1
{{- end }}