{{- $signingKeyJobEnabled := include "matrix-synapse.checkSigningKeyConfiguration" . | trim -}}
{{- if eq $signingKeyJobEnabled "true" }}
{{ $name := include "matrix-synapse.signingKeyFullName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.signingKeylabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - {{ $name }}
    verbs:
      - get
      - update
      - patch
{{- end }}