{{- if eq .Values.signingkey.existingSecret "" }}
{{ $name := include "matrix-synapse.signingKeyFullName" . }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: Delete=false
    argocd.argoproj.io/ignore-resource-updates: "true"
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.signingKeylabels" . | nindent 4 }}
data:
  signing.key: ""
{{- end }}