{{- $signingKeyJobEnabled := include "matrix-synapse.checkSigningKeyConfiguration" . | trim -}}
{{- if eq $signingKeyJobEnabled "true" }}
{{ $name := include "matrix-synapse.signingKeyFullName" . }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ $name }}
  labels:
    {{- include "matrix-synapse.signingKeylabels" . | nindent 4 }}
data:
  signing.key: ""
{{- end }}