{{- $signingKeyJobEnabled := include "matrix-synapse.checkSigningKeyConfiguration" . | trim -}}
{{- if eq $signingKeyJobEnabled "true" }}
{{ $name := include "matrix-synapse.signingKeyFullName" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    {{- include "matrix-synapse.signingKeylabels" . | nindent 4 }}
{{- end }}