{{- if .Values.persistence.enabled }}
{{- $fullName := include "thelounge.fullname" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-config
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if ne .Values.persistence.storageClassName "" }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
{{- end }}
{{- end }}